# Generated by Django 3.0.3 on 2020-03-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_app', '0004_auto_20200320_1458'),
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cart',
            name='add_item',
            field=models.ManyToManyField(blank=True, to='apply_app.Apply'),
        ),
    ]
