# Generated by Django 3.0.3 on 2020-03-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
                ('why', models.TextField()),
                ('service', models.TextField()),
                ('memory', models.TextField()),
                ('coding', models.TextField()),
            ],
        ),
    ]
