# Generated by Django 3.0.3 on 2020-03-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='url',
            field=models.TextField(),
        ),
    ]
